import { Op, type QueryInterface } from 'sequelize';

type MigrationContext = {
  context: QueryInterface;
};

export const subjectGroups: string[][] = [
  [
    'Agricultura Geral',
    'Química Geral e Bioquímica',
    'Cálculo Aplicado ao Agronegócio',
    'Botânica e Sistemática Vegetal',
    'Física Aplicada ao Agronegócio',
    'ESG',
    'Biologia Celular Aplicada ao Agronegócio',
    'Microbiologia Agrícola',
    'Gênese, Morfologia e Classificação do Solo',
    'Projeto de Extensão I',
    'Fisiologia Vegetal',
    'Estatística Básica Aplicada ao Agronegócio',
    'Tecnologia e Inovação',
    'Zoologia Geral',
    'Topografia Aplicada ao Agronegócio',
    'Projeto de Extensão II',
    'Experimentação Agrícola',
    'Agroecologia e Desenvolvimento Sustentável',
    'Zootecnia - Suinocultura, Avicultura e Equideocultura',
    'Genética Básica Aplicada ao Agronegócio',
    'Sensoriamento Remoto, Geoprocessamento e Georreferenciamento',
    'Manejo Integrado de Bacias Hidrográficas',
    'Fertilidade do Solo e Nutrição de Plantas',
    'Projeto de Extensão III',
    'Forragicultura e Nutrição Animal',
    'Administração Agroindustrial',
    'Olericultura',
    'Projeto de Extensão IV',
    'Zootecnia - Bovinocultura, Caprinocultura e Ovinocultura',
    'Máquinas e Implementos Agrícolas',
    'Agroclimatologia',
    'Agroindustrialização',
    'Gestão e Empreendedorismo',
    'Manejo e Conservação do Solo e Água',
    'Manejo de Plantas Daninhas',
    'Projeto de Extensão V',
    'Economia',
    'TCC I Aplicado ao Agronegócio',
    'Estágio Supervisionado I',
    'Entomologia Agrícola',
    'Fitotecnia - Mandioca, Café, Feijão e Algodão',
    'Fitopatologia',
    'Direitos Humanos, Diversidade e Inclusão',
    'Estágio Supervisionado II',
    'Hidráulica, Irrigação e Drenagem',
    'Métodos e Melhoramento de Plantas',
    'Inovação Tecnológica para a Agricultura',
    'Desenho Técnico e Construções Rurais',
    'Floricultura, Paisagismo, Parques e Jardins',
    'Estágio Supervisionado III',
    'Legislação Agrária, Avaliações e Perícias',
    'Fruticultura',
    'Tópicos Especiais I',
    'Fitotecnia - Arroz, Milho e Soja',
    'Produção e Tecnologia de Sementes',
    'Estágio Supervisionado IV',
    'Culturas Energéticas',
    'Piscicultura e Aquicultura',
    'Tópicos Especiais II',
    'Tecnologia de Aplicação de Defensivos',
    'TCC II Aplicado ao Agronegócio',
    'Silvicultura',
    'Sociologia e Extensão Rural',
  ],
  [
    'Matemática Básica',
    'Contabilidade Básica',
    'Introdução à Gestão Contemporânea',
    'Economia',
    'Introdução ao Estudo do Direito',
    'Comunicação Organizacional',
    'Gestão de Relacionamentos',
    'Legislação Empresarial e Tributária',
    'Tecnologia e Gestão do Conhecimento',
    'Práticas Econômicas',
    'Comportamento do Consumidor',
    'Comércio Exterior',
    'Contabilidade Empresarial',
    'Análises Financeiras nas Organizações',
    'Educação Ambiental e Sustentabilidade',
    'Gestão e Empreendedorismo',
    'Ética e Compliance',
    'Matemática Financeira',
    'Ferramentas Gerenciais',
    'Projeto de Extensão I',
    'Mercado Financeiro de Capitais',
    'Marketing Pessoal e Profissional',
    'Análise da Conjuntura Econômica',
    'Introdução ao Orçamento',
    'Fundamentos da Contabilidade Societária',
    'Legislação Tributária',
    'Projeto de Extensão II',
    'Legislação Trabalhista e Previdenciária',
    'Práticas Empreendedoras Contemporâneas',
    'Cálculo Atuarial',
    'Análise dos Sistemas Contábeis',
    'Controladoria Contábil',
    'Gestão Financeira e Orçamentária',
    'Práticas de Legislação Trabalhista e Previdenciária',
    'Cenário da Contabilidade Societária',
    'Ferramentas Estatísticas',
    'Projeto de Extensão III',
    'Práticas de Demonstrações Contábeis e Financeiras',
    'Contabilidade de Custos',
    'Formação em Perícia Contábil',
    'Noções de Contabilidade Tributária',
    'Contabilidade Digital',
    'Projeto de Extensão IV',
    'Estágio Supervisionado I',
    'Práticas de Legislação Tributária',
    'Introdução à Auditoria Contábil',
    'Imersão em Contabilidade de Custos',
    'Práticas de Perícia Contábil',
    'Contabilidade Pública e Governamental',
    'Contabilidade do Agronegócio',
    'Projeto de Extensão V',
    'Estágio Supervisionado II',
    'Estágio Supervisionado III',
    'Auditoria Contábil Avançada',
    'Aspectos da Contabilidade Tributária',
    'Projeto de Conclusão de Curso',
    'Contabilidade em Construção Civil',
    'Contabilidade Portuária e Aduaneira',
    'Planejamento Tributário',
    'Contabilidade Gerencial',
    'Contabilidade Bancária',
    'Análises Orçamentárias',
    'Trabalho de Conclusão de Curso',
    'LIBRAS',
    'Gestão da Qualidade',
    'Mercado Financeiro e de Capitais',
    'Gestão de Vendas',
    'Publicidade e Propaganda',
    'Marketing Digital',
    'Controle Estatístico da Qualidade',
    'Governança Corporativa',
    'Gestão do Agronegócio',
    'Auditoria',
    'Jogos de Empresas',
    'Formação de Gerentes',
    'Inovação Social',
    'Felicidade - Psicologia Positiva, Sentido e Propósito',
  ],
  [
    'Anatomia Humana',
    'Bioquímica',
    'Direitos Humanos e Diversidade',
    'Citologia/Histologia',
    'Educação Ambiental e Sustentabilidade',
    'Gestão e Empreendedorismo',
    'Microbiologia',
    'Laboratório Clínico',
    'Fisiologia Humana',
    'Bioestatística e Epidemiologia',
    'Imunologia',
    'Ética e Bioética em Saúde',
    'Análise Ambiental',
    'Genética',
    'Projeto de Extensão I',
    'Farmacologia Geral',
    'Patologia Geral',
    'Biologia Molecular e Biotecnologia',
    'Microbiologia e Tecnologia de Alimentos',
    'Imagenologia',
    'Projeto de Extensão II',
    'Gestão e Controle de Qualidade em Saúde',
    'Bacteriologia Clínica',
    'Micologia e Virologia Clínica',
    'Parasitologia Clínica',
    'Projeto de Extensão III',
    'Banco de Sangue',
    'Hematologia Clínica',
    'Imunologia Clínica',
    'Estética e Cosmetologia',
    'Projeto de Extensão IV',
    'Bioquímica Clínica',
    'Citologia Oncótica',
    'Líquidos Corporais',
    'Análises Toxicológicas',
    'Projeto de Extensão V',
    'Estágio Supervisionado em Análises Clínicas I',
    'Inovação na Biomedicina',
    'Projeto de Extensão VI',
    'Estágio Supervisionado em Análises Clínicas II',
    'Trabalho de Conclusão de Curso',
    'Felicidade - Psicologia Positiva, Sentido e Propósito',
    'Língua Brasileira de Sinais - LIBRAS',
  ],
  [
    'Lógica Computacional',
    'Algoritmos e Programação',
    'Matemática Aplicada',
    'Inglês Técnico',
    'Internet das Coisas',
    'Pensamento Computacional',
    'Introdução à Estrutura de Dados',
    'Cálculo Numérico',
    'Computação Gráfica',
    'Programação Orientada a Objetos',
    'Organização, Arquitetura de Computadores e Sistemas Operacionais',
    'Projeto de Extensão I',
    'Introdução a Banco de Dados',
    'Introdução à Programação para Web',
    'Introdução a Redes de Dispositivos Computacionais',
    'Geometria Analítica e Álgebra Linear',
    'Introdução ao Cálculo Diferencial e Integral',
    'Projeto de Extensão II',
    'Introdução ao Desenvolvimento para Dispositivos Móveis',
    'Banco de Dados',
    'Cálculo Diferencial e Integral',
    'Probabilidade e Estatística',
    'Estrutura de Dados',
    'Projeto de Extensão III',
    'Programação para Web',
    'Ciência de Dados e Aprendizagem de Máquina',
    'Introdução à Engenharia de Software',
    'Estágio Supervisionado I',
    'Projeto de Extensão IV',
    'Desenvolvimento para Dispositivos Móveis',
    'Engenharia de Software',
    'Computação Paralela e Distribuída',
    'Estágio Supervisionado II',
    'Projeto de Extensão V',
    'Introdução a Compiladores',
    'Desenvolvimento de Games',
    'Inteligência Artificial',
    'Automação e Robótica',
    'Trabalho de Conclusão de Curso I',
    'Teoria dos Grafos',
    'Interface Homem-Computador',
    'Trabalho de Conclusão de Curso II',
    'Segurança e Auditoria de Sistemas',
    'Redes de Dispositivos Computacionais',
    'Gerenciamento de Projetos',
    'Compiladores',
    'Qualidade e Auditoria de Software',
    'Organização do Trabalho',
    'Desenvolvimento de Produto',
    'Análise de Custos',
    'Gestão da Inovação',
    'Felicidade - Psicologia Positiva, Sentido e Propósito',
    'Língua Brasileira de Sinais - LIBRAS',
  ],
  [
    'Anatomia',
    'Fisiologia',
    'Bioquímica',
    'Histologia',
    'Imunologia',
    'Semiologia',
    'Patologia',
    'Farmacologia',
    'Cardiologia',
    'Endocrinologia',
    'Gastroenterologia',
    'Pediatria',
    'Clínica Médica',
    'Cirurgia Geral',
    'Ginecologia e Obstetrícia',
    'Saúde Coletiva',
    'Urgência',
  ],
  [
    'Teoria Geral do Direito',
    'História do Direito',
    'Criminologia',
    'Psicologia Jurídica e Relações Interpessoais',
    'Ciência Política e TGE',
    'Conceitos Básicos da Prática Forense e Habilidades Profissionais',
    'Direito Constitucional - Teoria da Constituição e Direitos Fundamentais',
    'Direito Civil - Parte Geral',
    'Teoria Geral do Processo',
    'Tecnologia e Inovação',
    'Direito Criminal - Penal 1',
    'Projeto de Extensão I',
    'Direito Constitucional - Organização do Estado e seus Poderes',
    'Direito Civil - Obrigações e Responsabilidade Civil',
    'Direito Processual Civil - Parte Geral e Tutela',
    'Direito Criminal - Penal 2',
    'Direitos Humanos, Diversidade e Inclusão',
    'Projeto de Extensão II',
    'Direito Civil - Direito dos Contratos e Relações de Consumo',
    'Direito Processual Civil - Instrução Processual e Recursos',
    'Gestão e Empreendedorismo',
    'Direito do Trabalho',
    'Projeto de Extensão III',
    'Direito Criminal - Penal 3',
    'Direito Processual Civil - Processo de Execução e Procedimentos Especiais',
    'Direito Criminal - Penal 4',
    'Processo Constitucional',
    'Direito Processual Penal I',
    'Direito Civil - Direito das Coisas',
    'Projeto de Extensão IV',
    'Direito Civil - Direito de Família',
    'Direito Processual Penal II',
    'Direito Administrativo Geral',
    'Métodos Adequados de Solução de Conflitos',
    'Clínica de Direitos Humanos',
    'Projeto de Extensão V',
    'Direito Administrativo - Contratos e Processos',
    'Prática em Técnicas de Audiência',
    'Processo do Trabalho',
    'Prática Criminal e Tribunal do Júri',
    'Direito Civil - Direito das Sucessões',
    'Direito Empresarial Geral',
    'Trabalho de Conclusão de Curso I',
    'Direito Tributário Geral',
    'Direito Previdenciário e Seguridade Social',
    'Ética, Deontologia e Gestão da Advocacia',
    'Prática Cível e Consumerista',
    'Trabalho de Conclusão de Curso II',
    'Direito Tributário - Normas Específicas',
    'Prática Trabalhista e Previdenciária',
    'Tópicos Especiais I',
    'Direito Ambiental e Agrário',
    'Direito Empresarial - Falência e Recuperação Empresarial',
    'Direito Internacional Público e Privado',
    'Tópicos Especiais II',
    'Práticas dos Métodos Adequados de Solução de Conflitos',
  ],
  [
    'Anatomia Humana',
    'História e Teoria da Enfermagem',
    'Citologia/Histologia',
    'Bioquímica',
    'Microbiologia',
    'Direitos Humanos e Diversidade',
    'Tecnologia e Gestão do Conhecimento',
    'Universidade, Enfermagem e a Vida Acadêmica',
    'Projeto de Extensão I',
    'Bases de Anatomia para Enfermagem',
    'Fisiologia Humana',
    'Embriologia, Genética e Evolução',
    'Educação Ambiental e Sustentabilidade',
    'Imunologia',
    'Parasitologia',
    'Patologia Geral',
    'Políticas Públicas e Atenção Primária à Saúde',
    'Projeto de Extensão II',
    'Semiologia e Semiotécnica Aplicada à Enfermagem',
    'Sistematização da Assistência em Enfermagem',
    'Cálculo e Administração de Medicamentos em Enfermagem',
    'Enfermagem em Saúde da Família e Comunidade',
    'Farmacologia Geral',
    'Estação de Aprendizado Saúde e Comunidade',
    'Projeto de Extensão III',
    'Gestão da Qualidade e Segurança do Paciente',
    'Fundamentos Aplicados à Enfermagem',
    'Psicologia Aplicada à Saúde',
    'Enfermagem em Centro Cirúrgico e Central de Material',
    'Ética e Bioética em Saúde',
    'Estação de Aprendizado Sistematização da Assistência de Enfermagem',
    'Projeto de Extensão IV',
    'Enfermagem em Saúde do Adulto',
    'Enfermagem em Saúde Coletiva',
    'Enfermagem em Saúde do Idoso',
    'Farmacologia Clínica',
    'Gestão e Empreendedorismo',
    'Estação de Aprendizado Bases para o Cuidado de Enfermagem',
    'Projeto de Extensão V',
    'Enfermagem em Saúde da Mulher e do Recém-Nascido',
    'Enfermagem em Saúde da Criança e do Adolescente',
    'Enfermagem em Doenças Tropicais e Transmissíveis',
    'Bioestatística e Epidemiologia',
    'Estação de Aprendizado Raciocínio Clínico na Assistência de Enfermagem',
    'Projeto de Extensão VI',
    'Enfermagem em Saúde Mental e Psiquiátrica',
    'Organização e Gestão em Saúde e Enfermagem',
    'Cuidados Paliativos em Enfermagem',
    'Enfermagem em Trauma e Emergência',
    'Ações Educativas em Enfermagem',
    'Estação de Aprendizado para Cuidados à Criança, Adolescente e Mulher',
    'Projeto de Extensão VII',
    'Marketing Pessoal e Profissional',
    'Trabalho de Conclusão de Curso I',
    'Estudo Interdisciplinar de Casos Clínicos',
    'Gerenciamento em Enfermagem',
    'Enfermagem em Unidade de Tratamento Intensivo',
    'Estação de Aprendizado Cuidados na Atenção Primária Especializada',
    'Estágio Curricular Supervisionado de Assistência de Enfermagem Hospitalar',
    'Estágio Curricular Supervisionado em Assistência de Enfermagem à Atenção Primária à Saúde',
    'Estágio Curricular Supervisionado de Enfermagem em Práticas Integrativas de Cuidado',
    'Trabalho de Conclusão de Curso II',
    'Estágio Curricular Supervisionado Gerencial de Enfermagem Hospitalar',
    'Estágio Curricular Supervisionado Gerencial de Enfermagem na Atenção Primária à Saúde',
    'Estágio Curricular Supervisionado em Assistência de Enfermagem em Ambulatório',
    'Atualizações em Enfermagem',
    'Enfermagem em Oncologia',
    'Inglês Instrumental',
    'Tratamento de Feridas e Lesões de Pele',
    'Auditoria em Saúde',
    'Estética Aplicada à Enfermagem',
    'Fundamentos Nutricionais e Dietéticos para o Cuidado de Enfermagem',
    'Eletrocardiograma',
    'Exames Diagnósticos',
    'Saúde do Trabalhador',
    'Práticas Integrativas e Complementares em Saúde',
    'Felicidade',
    'LIBRAS',
    'Felicidade - Psicologia Positiva, Sentido e Propósito',
  ],
  [
    'Anatomia Humana',
    'Química Geral',
    'Citologia/Histologia',
    'Química Orgânica',
    'Ciências Farmacêuticas, Saúde e Sociedade',
    'Tecnologia e Gestão do Conhecimento',
    'Atenção Primária à Saúde',
    'Fisiologia Humana',
    'Microbiologia',
    'Bioquímica',
    'Bioestatística e Epidemiologia',
    'Cálculo Farmacêutico',
    'Direitos Humanos e Diversidade',
    'Integração Escola, Serviço, Saúde e Comunidade',
    'Projeto de Extensão I',
    'Farmacologia Geral',
    'Imunologia',
    'Patologia Geral',
    'Atenção Pré-Hospitalar e Semiologia Farmacêutica',
    'Processos Físico-Químicos e Operações Unitárias',
    'Conduta Farmacoterapêutica',
    'Projeto de Extensão II',
    'Estágio I - Observacional',
    'Farmacologia Clínica',
    'Análise Química',
    'Manejo Clínico e Laboratorial de Doenças Bacterianas e Fúngicas',
    'Plantas Medicinais e Fitoterápicos',
    'Projeto de Extensão III',
    'Estágio II - Saúde Coletiva',
    'Manejo Clínico e Laboratorial de Doenças Parasitárias e Virais',
    'Farmacognosia',
    'Ética, Legislação e Assistência Farmacêutica',
    'Farmacotécnica',
    'Psicologia Aplicada à Saúde',
    'Projeto de Extensão IV',
    'Manejo Clínico e Laboratorial de Distúrbios Endócrinos e Metabólicos',
    'Tecnologia e Análise de Alimentos',
    'Cuidado Farmacêutico e Farmácia Clínica',
    'Projeto de Extensão V',
    'Estágio III - Farmácia Comunitária',
    'Cosmecêutica e Estética',
    'Genética, Biologia Molecular e Biotecnologia',
    'Análises Toxicológicas e Forenses',
    'Planejamento, Síntese e Análise de Fármacos',
    'Assuntos Regulatórios na Indústria Farmacêutica',
    'Projeto de Extensão VI',
    'Estágio IV - Farmácia Magistral',
    'Farmácia Hospitalar e Oncológica',
    'Processos Industriais e Tecnologia Farmacêutica',
    'Manejo Clínico e Laboratorial de Desordens Imuno-Hematológicas',
    'Práticas Integrativas e Complementares',
    'Gestão e Empreendedorismo',
    'Projeto de Extensão VII',
    'Estágio V - Farmácia Hospitalar e Farmácia Clínica',
    'Trabalho de Conclusão de Curso I',
    'Integração Clínico-Laboratorial',
    'Controle de Qualidade de Produtos Farmacêuticos',
    'Estágio VI - Ciências Farmacêuticas',
    'Trabalho de Conclusão de Curso II',
    'Atualidades em Ciências Farmacêuticas',
    'Marketing Pessoal e Profissional',
    'Educação Ambiental e Sustentabilidade',
    'Estágio VII - Análises Clínicas e Toxicológicas',
    'Língua Brasileira de Sinais - LIBRAS',
    'Segurança do Paciente e Farmacovigilância',
    'Farmacoepidemiologia',
    'Análise Ambiental',
    'Gestão de Recursos Humanos',
    'Felicidade - Psicologia Positiva, Sentido e Propósito',
  ],
  [
    'Citologia/Histologia',
    'Anatomia Humana',
    'Fundamentos de Fisioterapia na Prática da Profissão',
    'Biofísica',
    'Microbiologia',
    'Embriologia, Genética e Evolução',
    'Bioquímica',
    'Atenção Primária à Saúde',
    'Anatomia Humana Músculo-Esquelética',
    'Neuroanatomia Humana',
    'Cinesiologia e Biomecânica',
    'Fisiologia Humana',
    'Fisioterapia na Atenção Primária à Saúde',
    'Imunologia',
    'Saúde Coletiva',
    'Projeto de Extensão I',
    'Cinesioterapia',
    'Recursos Terapêuticos Manuais',
    'Fisiologia do Exercício',
    'Imagenologia e Exames Complementares',
    'Patologia Geral',
    'Socorros Urgentes',
    'Farmacologia Geral',
    'Projeto de Extensão II',
    'Recursos Eletrofísicos',
    'Métodos e Técnicas de Avaliação e Semiologia',
    'Crescimento e Desenvolvimento Humano',
    'Fisioterapia na Saúde do Trabalhador',
    'Bioestatística e Epidemiologia',
    'Projeto de Extensão III',
    'Fisioterapia Aquática',
    'Fundamentos de Fisioterapia Traumato-Ortopédica Funcional',
    'Fundamentos de Fisioterapia Neurofuncional',
    'Fisioterapia na Geriatria e Gerontologia',
    'Articulação Temporomandibular',
    'Fisioterapia nas Disfunções Reumatológicas',
    'Fisioterapia nas Doenças Crônicas Não Transmissíveis',
    'Fisioterapia em Uroginecologia e Obstetrícia',
    'Projeto de Extensão IV',
    'Fisioterapia Traumato-Ortopédica Funcional Aplicada',
    'Fisioterapia Neurofuncional Aplicada',
    'Fisioterapia nas Disfunções Cardiovasculares',
    'Fundamentos de Fisioterapia Pediátrica',
    'Fundamentos de Fisioterapia Pneumofuncional',
    'Fundamentos de Equoterapia',
    'Projeto de Extensão V',
    'Fisioterapia Pneumofuncional Aplicada',
    'Fisioterapia Pediátrica Aplicada',
    'Fisioterapia Desportiva',
    'Projeto de Extensão VI',
    'Estágio Supervisionado I',
    'Fisioterapia Hospitalar e Terapia Intensiva',
    'Órtese e Prótese',
    'Projeto de Pesquisa',
    'Projeto de Extensão VII',
    'Estágio Supervisionado II',
    'Fisioterapia Dermatofuncional',
    'Ética e Bioética em Saúde',
    'Direitos Humanos e Diversidade',
    'Gestão e Empreendedorismo em Saúde',
    'Estágio Supervisionado III',
    'Trabalho de Conclusão de Curso',
    'Tópicos Integradores',
    'Psicologia Aplicada à Saúde',
    'Educação Ambiental e Sustentabilidade',
    'Estágio Supervisionado IV',
    'Língua Brasileira de Sinais - LIBRAS',
    'Felicidade',
    'Realidade Virtual em Fisioterapia',
    'Fundamentos da Nutrição',
    'Cuidado Humano',
    'Interpretação Clínica de Exames Laboratoriais',
    'Teoria e Prática do Treinamento Esportivo',
    'Políticas Sociais - Educação, Saúde e Lazer',
    'Cineantropometria',
    'Fundamentos de Imunologia',
    'Fundamentos de Informática',
    'Saúde e Meio Ambiente',
    'Memória e Cultura Afro-Brasileira',
    'Atualidades em Fisioterapia',
    'Antropologia',
    'Auditoria em Saúde',
    'Biotecnologia',
    'Contabilidade Básica',
    'Deficiência Visual',
    'Educação Inclusiva I',
    'Educação Ambiental',
    'Estudo das Relações Étnico-Raciais no Brasil',
    'Inovação Tecnológica',
    'Matemática Financeira',
    'Métodos Estatísticos',
    'Reabilitação Profissional',
    'Transtornos do Espectro Autista',
    'Tópicos Especiais I',
    'Tópicos Especiais II',
    'Tópicos do Mundo Contemporâneo',
    'Anatomia Palpatória',
    'Fundamentos de Pilates',
    'Farmacologia Aplicada à Fisioterapia',
    'Tópicos Especiais em Fisioterapia',
    'Equoterapia',
    'Reabilitação Vestibular',
    'Felicidade - Psicologia Positiva, Sentido e Propósito',
  ],
  [
    'Anatomia do Sistema Locomotor de Animais Domésticos',
    'Biologia Celular',
    'Genética Aplicada às Ciências Agrárias',
    'Bioclimatologia e Zootecnia',
    'Histologia e Embriologia Veterinária',
    'Etologia e Bem-Estar Animal',
    'Estágio de Iniciação à Medicina Veterinária',
    'Bioquímica e Metabolismo Animal',
    'Fisiologia Veterinária',
    'Microbiologia Aplicada às Ciências Agrárias',
    'Ecologia e Desenvolvimento Sustentável em Produções Animais',
    'Projeto de Extensão I',
    'Esplancnologia e Neuroanatomia dos Animais Domésticos',
    'Microbiologia Veterinária Especial',
    'Parasitologia Veterinária',
    'Melhoramento Genético Animal',
    'Forrageiras e Manejo de Sistemas Pastoris',
    'Imunologia',
    'Projeto de Extensão II',
    'Patologia Veterinária Geral',
    'Farmacologia e Toxicologia Veterinária',
    'Epidemiologia Veterinária e Bioestatística',
    'Patologia Veterinária Sistêmica',
    'Nutrição de Poligástricos',
    'Nutrição de Monogástricos',
    'Sanidade Animal',
    'Projeto de Extensão III',
    'Semiologia e Laboratório Clínico de Animais de Companhia',
    'Medicina Veterinária Preventiva e Saúde Pública',
    'Terapêutica Veterinária',
    'Fisiopatologia da Reprodução da Fêmea',
    'Fisiopatologia da Reprodução do Macho',
    'Diagnóstico por Imagem Veterinário',
    'Produção e Manejo de Ruminantes',
    'Produção e Manejo de Não Ruminantes',
    'Semiologia e Laboratório Clínico de Animais de Produção',
    'Projeto de Extensão IV',
    'Clínica Médica de Animais de Companhia',
    'Clínica Médica de Poligástricos de Produção',
    'Clínica Médica de Aves e Suínos',
    'Clínica Médica de Equídeos',
    'Anestesiologia Veterinária',
    'Técnica Cirúrgica Veterinária',
    'Clínica Cirúrgica Veterinária',
    'Projeto de Extensão V',
    'Higiene e Inspeção de Leite e Produtos Derivados',
    'Higiene e Inspeção de Carne e Produtos Derivados',
    'Higiene e Inspeção de Ovos, Mel e Pescado',
    'Tecnologia de Produtos de Origem Animal',
    'Inspeção e Tecnologia de Produtos de Origem Animal',
    'Diagnóstico Post-Mortem e Medicina Veterinária Legal',
    'Zoonoses e Saúde Única',
    'Zootecnia, Produção e Reprodução Animal',
    'Administração Rural',
    'Ética e Deontologia Veterinária',
    'Projeto de Extensão VI',
    'Tópicos Contemporâneos em Medicina Veterinária',
    'Estágio Supervisionado Interno em Medicina Veterinária',
    'Estágio Supervisionado Externo em Medicina Veterinária',
    'Trabalho de Conclusão de Curso',
    'Gestão e Empreendedorismo em Saúde',
    'Clínica e Manejo de Animais Silvestres',
    'Oncologia Veterinária',
    'Dermatologia Veterinária',
    'Odontologia Veterinária',
    'Sociologia e Extensão Rural',
    'Felicidade - Psicologia Positiva, Sentido e Propósito',
  ],
];

export const subjectGroupCourseCodes = [
  'agronomia',
  'ciencias-contabeis',
  'biomedicina',
  'ciencia-computacao',
  'medicina',
  'direito',
  'enfermagem',
  'farmacia',
  'fisioterapia',
  'medicina-veterinaria',
] as const;

if (subjectGroups.length !== subjectGroupCourseCodes.length) {
  throw new Error('Os grupos de matérias não correspondem aos cursos de origem.');
}

const subjectNames = [...new Set(subjectGroups.flat())].sort((left, right) =>
  left.localeCompare(right, 'pt-BR'),
);

export function toSubjectCode(name: string): string {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '');
}

const subjectRows = subjectNames.map((name) => ({ code: toSubjectCode(name), name }));
const subjectCodes = subjectRows.map(({ code }) => code);

if (new Set(subjectCodes).size !== subjectCodes.length) {
  throw new Error('O catálogo inicial de matérias contém códigos duplicados.');
}

export async function up({ context: queryInterface }: MigrationContext): Promise<void> {
  await queryInterface.sequelize.transaction(async (transaction) => {
    const now = new Date();
    const auditValues = {
      created_at: now,
      created_by: null,
      deleted_at: null,
      deleted_by: null,
      updated_at: now,
      updated_by: null,
    };

    await queryInterface.bulkInsert(
      'subjects',
      subjectRows.map(({ code, name }) => ({
        ...auditValues,
        code,
        is_active: true,
        name,
      })),
      { transaction },
    );
  });
}

export async function down({ context: queryInterface }: MigrationContext): Promise<void> {
  await queryInterface.sequelize.transaction(async (transaction) => {
    await queryInterface.bulkDelete(
      'subjects',
      { code: { [Op.in]: subjectCodes } },
      { transaction },
    );
  });
}
